package com.alium.nibo.utils;

/**
 * Created by abdulmujibaliu on 9/7/17.
 */

public interface NiboConstants {

    String SEARCHBAR_TITLE_ARG = "SEARCHBAR_TITLE";
    String SELECTION_BUTTON_TITLE = "SELECTION_BUTTON_TITLE";
    String STYLE_ENUM_ARG = "STYLE_ENUM_ARG";
    String STYLE_FILE_ID = "STYLE_FILE_ID";
    String MARKER_PIN_ICON_RES = "MARKER_PIN_ICON_RES";

    String _FRAGMENT_TAG = "_FRAGMENT_TAG";

    String RESULTS_SELECTED = "RESULTS_SELECTED";


    String ORIGIN_EDIT_TEXT_HINT_ARG = "ORIGIN_EDIT_TEXT_HINT_ARG";
    String DEST_EDIT_TEXT_HINT_ARG = "DEST_EDIT_TEXT_HINT_ARG";
    String ORIGIN_MARKER_ICON_RES_ARG = "ORIGIN_MARKER_ICON_RES_ARG";
    String DEST_MARKER_ICON_RES_ARG = "DEST_MARKER_ICON_RES_ARG";
    String BACK_BUTTON_ICON_RES_ARG = "BACK_BUTTON_ICON_RES_ARG";
    String TEXT_FIELD_CLEAR_ICON_RES_ARG = "TEXT_FIELD_CLEAR_ICON_RES_ARG";
    String DONE_FAB_ICON_RES_ARG = "DONE_FAB_ICON_RES_ARG";
    String BACK_BTN_COLOR_RES_ARG = "BACK_BTN_COLOR_RES_ARG";
    String ORIGIN_CIRCLE_VIEW_COLOR_RES_ARG = "ORIGIN_CIRCLE_VIEW_COLOR_RES_ARG";
    String DEST_CIRCLE_VIEW_COLOR_RES_ARG = "DEST_CIRCLE_VIEW_COLOR_RES_ARG";
    String ORIG_DEST_SEPERATOR_LINE_COLOR_RES_ARG = "ORIG_DEST_SEPERATOR_LINE_COLOR_RES_ARG";
    String DONE_FAB_COLOR_RES_ARG = "DONE_FAB_COLOR_RES_ARG";


}
