package com.alium.nibo.utils;

/**
 * Created by abdulmujibaliu on 9/7/17.
 */

public interface NiboConstants {

    String SEARCHBAR_TITLE_ARG = "SEARCHBAR_TITLE";
    String SELECTION_BUTTON_TITLE = "SELECTION_BUTTON_TITLE";
    String STYLE_ENUM_ARG = "STYLE_ENUM_ARG";
    String STYLE_FILE_ID = "STYLE_FILE_ID";
    String MARKER_PIN_ICON_RES = "MARKER_PIN_ICON_RES";

    String _FRAGMENT_TAG = "_FRAGMENT_TAG";

    String SELECTED_PLACE_RESULT = "SELECTED_PLACE_RESULT";

    String SELECTED_ORIGIN_DESTINATION_RESULT = "SELECTED_ORIGIN_DESTINATION_RESULT";

    String ORIGIN_EDIT_TEXT_HINT_ARG = "ORIGIN_EDIT_TEXT_HINT_ARG";
    String DEST_EDIT_TEXT_HINT_ARG = "DEST_EDIT_TEXT_HINT_ARG";
    String ORIGIN_MARKER_ICON_RES_ARG = "ORIGIN_MARKER_ICON_RES_ARG";
    String DEST_MARKER_ICON_RES_ARG = "DEST_MARKER_ICON_RES_ARG";
    String BACK_BUTTON_ICON_RES_ARG = "BACK_BUTTON_ICON_RES_ARG";
    String TEXT_FIELD_CLEAR_ICON_RES_ARG = "TEXT_FIELD_CLEAR_ICON_RES_ARG";

    String PRIMARY_POLY_LINE_COLOR_RES = "PRIMARY_POLY_LINE_COLOR_RES";
    String SECONDARY_POLY_LINE_COLOR_RES = "SECONDARY_POLY_LINE_COLOR_RES";

    String ORIGIN_CIRCLE_VIEW_COLOR_RES_ARG = "ORIGIN_CIRCLE_VIEW_COLOR_RES_ARG";
    String DEST_CIRCLE_VIEW_COLOR_RES_ARG = "DEST_CIRCLE_VIEW_COLOR_RES_ARG";
    String ORIG_DEST_SEPERATOR_LINE_COLOR_RES_ARG = "ORIG_DEST_SEPERATOR_LINE_COLOR_RES_ARG";
    String DONE_FAB_COLOR_RES_ARG = "DONE_FAB_COLOR_RES_ARG";



    String OK = "OK";
    String NOT_FOUND = "NOT_FOUND";
    String ZERO_RESULTS = "ZERO_RESULTS";
    String MAX_WAYPOINTS_EXCEEDED = "MAX_WAYPOINTS_EXCEEDED";
    String INVALID_REQUEST = "INVALID_REQUEST";
    String OVER_QUERY_LIMIT = "OVER_QUERY_LIMIT";
    String REQUEST_DENIED = "REQUEST_DENIED";
    String UNKNOWN_ERROR = "UNKNOWN_ERROR";


    String API_KEY_PARAM = "API_KEY_PARAM";
    String LATITUDE_PARAM = "LATITUDE_PARAM";
    String LONGITUDE_PARAM = "LONGITUDE_PARAM";
    String PLACE_ID_PARAM = "PLACE_ID_PARAM";

    String ORIGIN_PARAM = "ORIGIN_PARAM";
    String DESTINATION_PARAM = "DESTINATION_PARAM";
    String SUGGESTION_QUERY_PARAM = "SUGGESTION_QUERY_PARAM";
    String SUGGESTION_ITEM_PARAM = "SUGGESTION_ITEM_PARAM";


    String BASE_DIRECTIONS_URL = "https://maps.googleapis.com";

}
